[client]
showErrorDetails = false

[runner]
magicEnabled = false

[server]
fileWatcherType = "none"
headless = true

[browser]
gatherUsageStats = false

[theme]
primaryColor="#763737"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#f2f2f2"
textColor="#262730"
font="sans-serif"
