name: ghcr.io try-out

on: push

jobs:
  build-streamlit-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 'Get Previous tag'
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
    - name: Build and push to ghcr.io
      uses: docker/build-push-action@v2
      with:
        context: streamlit
        push: true
        tags: ghcr.io/compomics/deeplc-streamlit:${{ steps.previoustag.outputs.tag }}
